from classes import Abalone

if __name__ == "__main__":
    jogo = Abalone() # Cria um jogo
    jogo.movimentar_peca((0, 1), "bd")
    jogo.movimentar_peca((1, 2), "bd")
    jogo.movimentar_peca((2, 3), "bd")
    jogo.movimentar_peca((3, 4), "bd")
    jogo.imprimir_tabuleiro()
    print(jogo.funcao_utilidade((4, 5)))
    # jogo.movimentar_peca((8, 2), "ce")
    # jogo.movimentar_peca((7, 2), "ce")
    # jogo.movimentar_peca((6, 4), "e")
    # jogo.movimentar_peca((6, 3), "e")
    # jogo.movimentar_peca((8, 1), "ce")
    # jogo.movimentar_peca((7, 1), "ce")
    # jogo.movimentar_peca((8, 0), "ce")
    # jogo.movimentar_peca((7, 0), "ce")
    # jogo.movimentar_peca((6, 2), "ce")
    # jogo.movimentar_peca((5, 0), "cd")
    # jogo.movimentar_peca((4, 1), "cd")
    # jogo.movimentar_peca((3, 1), "cd")
    # jogo.movimentar_peca((2, 1), "cd")
    # jogo.imprimir_tabuleiro()
    # jogo.jogar()
